<a href="https://colab.research.google.com/github/pratyasha7/Infosys_BudgetWise-AI-Expense-Forecasting-Tool/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Initializing NumPy Array with Zeros

In [1]:
import numpy as np

In [2]:
n1=np.zeros((1, 2))

In [3]:
n1


array([[0., 0.]])

Initializing NumPy Array with Same Number

In [4]:
n1=np.full((2, 2), 10)


In [5]:
n1

array([[10, 10],
       [10, 10]])

Initializing NumPy Array within a Range


In [6]:
n1=np.arange(10, 20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
n1=np.arange(10, 50, 5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

Initializing NumPy Array with Random Numbers


In [8]:
n1=np.random.randint(1, 100, 5)
n1

array([39, 40, 11, 65,  7])

Checking and Changing NumPy Array Shape

In [9]:
n1=np.array([[1, 2, 3], [4, 5, 6]])
n1.shape


(2, 3)

In [10]:
n1.shape = (3, 2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

Joining NumPy Arrays

In [11]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [13]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

NumPy Intersection & Difference (Set Operations)

In [14]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

In [15]:
np.intersect1d(n1,n2)

array([50, 60])

In [16]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [17]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

Addition of Numpy Arrays

In [18]:
n1=np.array([10,20])
n2=np.array([30,40])
np.sum([n1,n2])

np.int64(100)

In [19]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [20]:
np.sum([n1,n2],axis=1)

array([30, 70])

NumPy Array Mathematics

In [21]:
n1=np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [22]:
n1=n1-1
n1

array([10, 20, 30])

In [23]:
n1=n1*2
n1

array([20, 40, 60])

In [24]:
n1=n1/2
n1

array([10., 20., 30.])

NumPy Statistical Functions

In [25]:
n1=np.array([10,20,30,40,50,60])
np.mean(n1)

np.float64(35.0)

In [26]:
n1=np.array([11, 4, 5, 96, 67, 85])
np.median(n1)

np.float64(39.0)

In [27]:
n1=np.array([1, 5, 3, 100, 4, 48])
np.std(n1)

np.float64(36.59424666377065)

Matrix Multiplication

In [28]:
n1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
n2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
n1.dot(n2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [29]:
n2.dot(n1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])